# Generated by Django 5.2 on 2026-03-05 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractivePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('regions', models.ManyToManyField(blank=True, related_name='interactive_pages', to='kiosk.region')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
