# Generated by Django 5.2 on 2026-03-05 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EKiosk',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('force_update', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_interval', models.PositiveIntegerField(default=300)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_app_version', models.CharField(blank=True, max_length=50)),
                ('last_os_version', models.CharField(blank=True, max_length=50)),
                ('last_storage_free', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_memory_free', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_known_hash', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KioskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('reported_hash', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_up_to_date', models.BooleanField()),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kiosk.ekiosk')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='ekiosk',
            name='playlist_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_overrides', to='kiosk.playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='kiosk.region'),
        ),
        migrations.AddField(
            model_name='ekiosk',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosks', to='kiosk.region'),
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_items', to='media_manager.media')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kiosk.playlist')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('playlist', 'order')},
            },
        ),
    ]
