# Generated by Django 5.2 on 2026-03-06 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_alter_ekiosk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='region',
        ),
        migrations.AddField(
            model_name='region',
            name='active_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_regions', to='kiosk.playlist'),
        ),
    ]
