# Generated by Django 5.2 on 2026-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_remove_playlist_region_region_active_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekiosk',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ekiosk',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ekiosk',
            name='stop_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
