# Generated by Django 5.2 on 2026-03-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_kiosklog_app_version_kiosklog_memory_free_kiosklog_storage_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekiosk',
            name='last_app_state',
            field=models.CharField(blank=True, choices=[('foreground', 'Foreground'), ('background', 'Background'), ('terminated', 'Terminated')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='kiosklog',
            name='app_state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='kiosklog',
            index=models.Index(fields=['checked_at'], name='kiosk_kiosk_checked_d9a9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='kiosklog',
            index=models.Index(fields=['kiosk', '-checked_at'], name='kiosk_kiosk_kiosk_i_f613bc_idx'),
        ),
    ]
